version: '3.2'

services:
  web:
    build:
      context: './docker/'
      args:
        PHP_VERSION: ${PHP_VERSION}
    volumes:
      - ./:/var/www/
      - ./docker/vhost/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    ports:
      - "${APACHE_HTTP_PORT}:80"
    stdin_open: true
    tty: true

  redis:
    image: redis:5.0-alpine
    ports:
      - "6379:6379"
